### ISSUE TITLE
resize image - scale

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js#11]

**Comment by lpatiny** [comment]
Size could be given in percentage or pixels, the transform may be proportional or not
{width:'100%'}
{height:'100'} // means the height will be 100 pixels and it is a proportional transform
{width:'120%', height:100} : non proportional transform. The width will have 120% of the current size and the height, 100 pixels

**Comment by targos** [comment]
https://github.com/image-js/core/issues/65

**Comment by targos** [comment]
* sampling (discard rows / columns)
* average ?
* ...

**Comment by lpatiny** [comment]
For  sampling I think this should be the way to select:

An example

1 1 0 0 1


5 pts -> 2 pts

To calculate increment we remove one to the original size
increment : (5 - 1) / 2 = 2
First value -> increment / 2 = 1
Next value -> 1 + 2 = 3

Result : 1 0


5 pts -> 3 pts
increment : (5 - 1) / 3 = 1.33
First value -> increment / 2 = 0.66

Point 0 : 0.66 -> Math.round -> 1
Point 1 : 0.66 + 1.33 = 2
Point 2 : 0.66 + 2 * 1.33 = 3.33 -> Math.round -> 3

Result : 1 0 0


I have updated the code at:
http://codeshare.io/vKLaq

**Comment by cballesteros** [comment]
This is interesting:
https://campusvirtual.univalle.edu.co/moodle/pluginfile.php/666825/mod_resource/content/1/Subsampling.pdf
