### ISSUE TITLE
jsdoc does not generate correctly the documentation ?

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js#226]
I added a link:

https://github.com/image-js/core/blob/master/src/image/transform/rgba8.js#L11

And documentation.js create a link like:

https://image-js.github.io/core/#imagegetrgbadata

So the link is convert to lowercase and removed of the .

The correct one should be:

https://image-js.github.io/core/#Image#getRGBAData

So I don't know where is the mistake ... @targos you could help ?

**Comment by targos** [comment]
why don't you ask on the documentation repo ?

**Comment by lpatiny** [comment]
Maybe there was an obvious mistake but I will do.

**Comment by targos** [comment]
I don't see an obvious mistake

**Comment by targos** [comment]
this was fixed in a documentationjs upgrade
