### ISSUE TITLE
More on interpolation

### ISSUE THREAD

**Issue by targos** [image-js/image-js#271]
http://photocreations.ca/interpolator/index.html
http://www.panoramafactory.com/quality/quality.html
http://web.archive.org/web/20090626095428/http://www.all-in-one.ee/~dersch/interpolator/interpolator.html

**Comment by targos** [comment]
[paeth.pdf](https://github.com/image-js/core/files/626567/paeth.pdf)
[interpolation.pdf](https://github.com/image-js/core/files/626568/interpolation.pdf)

**Comment by andcastillo** [comment]
There is a 2D regresión algorithm in ml. if you use it with the minimun number of points for each polinomial degree you have an interpolation function. https://github.com/mljs/regression/blob/master/test/2d-polinomial-fit.js

**Comment by targos** [comment]
it's about pixel-wise interpolation (image resizing or rotation). If we have to train a new regression model for each pixel I'm afraid it will take too much time
