### ISSUE TITLE
Documenting array, array of objects and array of Array

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js#275]
It seems that an array of object should be documented by adding a '.' after the array. @targos What do you think we should change this everywhere ?

```
@param{Array.<{name:string, email:string}>}
```

http://usejsdoc.org/tags-type.html

http://stackoverflow.com/questions/17163897/how-do-you-document-an-array-of-objects-as-a-parameter-in-jsdoc

**Comment by lpatiny** [comment]
@stropitek we should try to keep it constant in all the projects (and also spectra-data)

**Comment by maasencioh** [comment]
@lpatiny but currently the documentation generator accepts this format also, so We shouldn't change in all the projects that currently have this standard
