### ISSUE TITLE
Sobel operator

### ISSUE THREAD

**Issue by JeffersonH44** [image-js/image-js#300]
the sobel operator is returning and image with a Uint8ClampedArray in the return statement, it should return a Float32Array image for the derivatives, no? and the convolutions made inside the functions uses the Float32Array.

**Comment by lpatiny** [comment]
6dbf0e37233826cde8d6aebe870ba8bc9387b774
I added an option allowing to specify the bitDepth in the resulting image and updated the documentation.
I'm not sure what should be the default behaviour on the other end. float32 seems exaggerated for a 8 bit image.

**Comment by JeffersonH44** [comment]
now that I'm seeing how works that bitDepth of 32, I saw that for each pixel you have 4 values all inside of a Float32Array and I supposed that it's ok, what I'm saying is that for those derivatives you should return an image with a Float32Array instead of the Uint8ClampedArray because you can also have negative derivatives, no?

**Comment by lpatiny** [comment]
I don't think we can have negative value because we do an hypotenuse between the derivative along X and derivative along Y. Or we did something wrong ?

**Comment by JeffersonH44** [comment]
Sorry, it's ok, thanks.
