### ISSUE TITLE
loading jpeg withcredentials

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js#328]
currently we can load tif and png withCredential but it does not work when we try to load a jpg

@targos

**Comment by targos** [comment]
If it's a cross-origin request, it won't be possible until we have a JavaScript decoder.

**Comment by lpatiny** [comment]
I'm a little bit lost ... If we load a PNG or TIF from URL we first load the binary and then send the binary to the library. We are not doing the same for jpg ? Because we also need to binary to extract the meta information from the jpg so I would expect we can send a base64 encode binary (or binary ?) directly to the canvas ?

**Comment by targos** [comment]
Please try with http://www.lactame.com/lib/image-js/0.11.10/ I cannot test this on the browser

**Comment by lpatiny** [comment]
@targos  Many thanks it works !
