### ISSUE TITLE
convolution using a kernel

### ISSUE THREAD

**Issue by targos** [image-js/image-js#33]
https://en.wikipedia.org/wiki/Kernel_(image_processing)

**Comment by MariaTrujillo** [comment]
Alvaro has an implementation of convolution operation for the median filter, using the 1D image array

**Comment by lpatiny** [comment]
Any possibility to make a pull request so that we have a look to the code before tomorrow meeting ?

**Comment by targos** [comment]
The convolution filter should accept as kernel an array (1d) or a matrix (array 2d).
If 1D: the square root of the number of elements should be an integer, otherwise throw a RangeError. Then consider the values row by row:
```
[0, 1, 2, 3, 4, 5, 6, 7, 8] ->
0 1 2
3 4 5
6 7 8
```
If 2D array, it may not be square ! Accept rectangular matrices.
The good method to check if an object is an array: `Array.isArray(obj)`
TBD: number of rows and columns should be odd ?

It returns a smaller image (no copy of border pixels). If the same size is required, we should use the padding library first.

https://github.com/image-js/core/issues/65

**Comment by targos** [comment]
Interesting links:
http://designstacks.net/convolution-matrix
http://rsbweb.nih.gov/ij/docs/guide/146-29.html
http://docs.gimp.org/en/plug-in-convmatrix.html
