### ISSUE TITLE
Examples in readme use a different image

### ISSUE THREAD

**Issue by stropitek** [image-js/image-js#406]
The demos don't use the taxi image but instead a grey image.

The processing has no effect in some cases or fails in other.

@lpatiny

**Comment by targos** [comment]
For me it's a football stadium...

**Comment by targos** [comment]
You can just put the example image in the repo (like for SEM/TEM)

**Comment by lpatiny** [comment]
closed by fd21ee5897897c8cd92f3c0ccc3a84c3218372ee
