### ISSUE TITLE
problems with dependencies?

### ISSUE THREAD

**Issue by fish-bytes** [image-js/image-js#410]
Working on an IONIC app on Android, getting errors with the Image-JS loading, when trying to run it.

It seems like a dependency error, but I will let the experts review :)

I get errors such as "class PNGDecoder extends __WEBPACK_IMPORTED_MODULE_0_iobuffer__["default"] {

I had been getting an error for IOBuffer missing and installed via npm install iobuffer, which got me this far.

If I run version 0.14.4 the app runs, but has some other issues with functions not working quite right, which I'm not surprised about since 14 is a rather old version.  0.14.4 is the latest version that will run for me.

This is an IONIC v3 app on Android

**Comment by targos** [comment]
I do not know Ionic but this is probably because the javascript engine used in this case is too old to understand the syntax used in the PNGDecoder class.
The only piece of advise I can give is to use a transpiler such as Babel to convert the dependencies to an older syntax.
