### ISSUE TITLE
Compatible with WKWebView?

### ISSUE THREAD

**Issue by p3v9d5ui** [image-js/image-js#466]
Hi Everyone,

I use image-js in my Cordova (iOS & Android) application, and it has been working fine. But, I've just swiched to the WKWebView engine, in place of UIWebView, which is deprecated. Now, however, ImageJs.load(), with a file path as input, no longer works, and the error that's thrown doesn't seem to have any useful information. Has anyone else gotten this to work with WKWebView ?

**Comment by targos** [comment]
Hi! What does the file path look like?
I'm not familiar with mobile web view engines).

**Comment by p3v9d5ui** [comment]
Hi @targos 

Previous to switching to WKWebView, I would start with a path like this:

file:///var/containers/Bundle/Application/077BB63A-EBC8-46B7-A193-58AC0CCF5641/<app-name>/www/card_images/card1.jpg

Which I would then convert to an internal URL using resolveLocalFileSystemURL() and toInternalURL() which would result in a URL like this: 

cdvfile://localhost/bundle/www/card_images/card1.jpg

This "cdvfile" URL is what I pass to ImageJs.load(), and this worked fine.

This stopped working with WKWebView, and I've tried using all of these variations, without success:

file:///var/containers/Bundle/Application/077BB63A-EBC8-46B7-A193-58AC0CCF5641/<app-name>/www/card_images/card1.jpg

/var/containers/Bundle/Application/077BB63A-EBC8-46B7-A193-58AC0CCF5641/<app-name>/www/card_images/card1.jpg

cdvfile://localhost/bundle/www/card_images/card1.jpg

**Comment by targos** [comment]
In a browser environment, we use XMLHttpRequest to load from a URL:

https://github.com/image-js/image-js/blob/3f19c2bc4d68763b7f77ff50723c3e325811bba2/src/browser/environment.js#L12-L26

Maybe in WKWebView, it is not allowed anymore?
If you have another way to load the files into an ArrayBuffer or a TypedArray, you could also directly pass one to `Image.load()`

**Comment by p3v9d5ui** [comment]
Hi @targos. Yes, that's the exact issue. XMLHttpRequest does not work with WKWebView due to CORS. I will look into reading the file data using a different method.
