### ISSUE TITLE
selecting color of background when converting from png to jpg

### ISSUE THREAD

**Issue by FunnyB0y** [image-js/image-js#485]
Converting a png with a transparent background to jpg will change that color to black by default. Is there anyway to change this color? I can't see to find any API that can do this. It seems like `.background` would be a candidate but the documentation isn't very clear on what it does.

**Comment by targos** [comment]
Hi, to do this you would need to convert the transparent pixels to white. Here is a way this can be done:

```js
// Load the image.
const image = await Image.load('image.png');
// Get the alpha channel.
const alpha = image.getChannel(3);
// Create a binary mask on the transparent pixels (255 = opaque).
const mask = alpha.mask({ threshold: 254, invert: true });
// Paint the pixels from the mask in white.
image.paintMasks(mask, { color: 'white' });
// Save the image as jpg.
await image.save('image.jpg');
```

`.background` is another method that tries to remove the "noise" in the background of an image to enhance it for use in other algorithms.

**Comment by FunnyB0y** [comment]
Just wanted to note that `.getChannel`'s value is between 0 and 2, seems to work for 2.

**Comment by targos** [comment]
That's weird. I tested my script and PNGs always have 4 channels (RGBA)

**Comment by FunnyB0y** [comment]
That would make sense, but inputing 3 gives me this error:

`RangeError: validateChannel : the channel has to be >=0 and <3`

**Comment by toyssamurai** [comment]
There's a problem with this solution -- the mask is binary and the anti-aliasing edges would be lost. Does anyone know of a way that can keep the anti-aliasing?
