### ISSUE TITLE
blurFilter - RangeError: validateKernel: Kernel array should be a square

### ISSUE THREAD

**Issue by FunnyB0y** [image-js/image-js#486]
I am getting the error:

`RangeError: validateKernel: Kernel array should be a square`

when I'm using `.blurFilter`

My code is straight out of the documentation

* temp_inst is just the loaded instance, i.e. `imagejs.load(s_input_file)`

        temp_inst
            .blurFilter({
                radius:
                    3
            })

**Comment by targos** [comment]
Yeah, there's apparently a bug in the blurFilter function. I'll have a look.

**Comment by targos** [comment]
It should be fixed in v0.21.7
