### ISSUE TITLE
getValueXY works with integers only

### ISSUE THREAD

**Issue by ovanderzee** [image-js/image-js#502]
I am developing a node module for use in the browser, using '../node_modules/image-js/dist/image'.
When I call getValueXY with broken numbers for x or y, I get unexpected results.
Mostly I see RGBA like [undefined, undefined, undefined, undefined].
But when I call with quarter values, getValueXY(72.25, 80.75), I get values that look right, but are not. 

Of course I can use Math.floor to convert the coordinates, but the behaviour looks unwanted.

**Comment by incanus** [comment]
Another vote for this — it would be nice in the main functionality. I too was bitten by this and needed to use `Math.floor()`.

**Comment by lpatiny** [comment]
Checking or rounding the numbers takes some time and when you want to apply millions of operations it is not a good idea to do so and this is why we don't.

We assume that the user of the library would give integer numbers for the coordinates and I don't think this should be unexpected.
