### ISSUE TITLE
[Question] Can't figure out how to create transparent PNG

### ISSUE THREAD

**Issue by trsh** [image-js/image-js#504]
```
const { Image } = require('image-js');
var image = new Image(800, 600, {alpha: 0, kind: 'RGBA'});
image.save("test.png");
```

turns black :(

**Comment by owenmcateer** [comment]
Two things I can see. You need to set alpha to true(1). And in the latest version, you need to provide a data array. It needs to be width*height*channels and have some value.

`
const { Image } = require('image-js');
var image = new Image(800, 600, new Array(800 * 600 * 4).fill(0), {alpha: 1, kind: 'RGBA'});
image.save("test.png");
`

**Comment by lpatiny** [comment]
It seems to me also that if you have value of '0' on alpha channel the image will be black.

I also think that kind 'RGBA' should set the alpha correctly to 1. Using types array may also improve the performances.

So this example yield correctly to a white image:
```
const { Image } = require("image-js");
var image = new Image(800, 600, new Uint8Array(800 * 600 * 4).fill(255), {
  kind: "RGBA",
});
image.save("test.png");
```
