### ISSUE TITLE
TypeError: image1.match is not a function

### ISSUE THREAD

**Issue by mengjiaowang** [image-js/image-js#507]
Hello, 

I was trying to use the match function in this library, but I got an error. 

`
const { Image } = require('image-js')

async function run () {
    const image1 = await Image.load('img1.png')
    const image2 = await Image.load('img2.png')
    image1.match(image2)
}
run()
`

TypeError: image1.match is not a function
    at run (/Users/Projects/scripts/nodejs/image_match.js:6:12)

Instead of using match, I also tried to use image1.save("img_cpoy.img") and it worked for me. The version I used is as below:

npm v image-js
image-js@0.21.9 | MIT | deps: 24 | versions: 69
Image processing and manipulation in JavaScript
https://github.com/image-js/core

**Comment by lpatiny** [comment]
Mistake in the documentation. It should be `getBestMatch`
