### ISSUE TITLE
cannyEdge: are there any Samples

### ISSUE THREAD

**Issue by jagnarock** [image-js/image-js#514]
Hi guys.
Thank you for this really good image processing library.
Are there any samples for the function cannyEdge?
Or: which options/parameters I can use in this function?
https://image-js.github.io/image-js/#imagecannyedge

**Comment by stropitek** [comment]
The just forwards the options to this library: https://www.npmjs.com/package/canny-edge-detector

**Comment by jagnarock** [comment]
> The method just forwards the options to this library: https://www.npmjs.com/package/canny-edge-detector

Cool, thx for the hint
