### ISSUE TITLE
Memory allocation error for large images

### ISSUE THREAD

**Issue by matthewjosephtaylor** [image-js/image-js#518]
context: jpeg-js has a default max memory size of 512mb.

Loading a jpeg image via `Image.load` that decodes to larger than default max memory creates an error like

```
maxMemoryUsageInMB limit exceeded by at least 117MB
```

I was able to work around this by patching the load.js code:

```
const jpeg = decodeJpeg(data, { useTArray: true, maxMemoryUsageInMB: 1024 });
```

Here is my fork of the repo with the fix in place https://github.com/matthewjosephtaylor/image-js/commit/2094388f51776257f9f82457d58c81a9e6bdae2c

It feels like it would be good for the load function to take an optional max-memory setting.

Will submit a PR but I'm not proud of the fix, and think a better API for load might be called for. :)

**Comment by matthewjosephtaylor** [comment]
PR https://github.com/image-js/image-js/pull/519

**Comment by targos** [comment]
Thanks for the PR!
