### ISSUE TITLE
[support] Why does countAlphaPixels not work?

### ISSUE THREAD

**Issue by santosh** [image-js/image-js#544]
```js
const { Image } = require('image-js');

async function main() {
  let image = await Image.load("color_diff.png");
  let num = image.countAlphaPixels();
  console.log(num);
}

main()
```

Below is the test image with alpha channel, 250 x 250 px. The center is color with black. I was expecting the number of pixels that cover the black mark. 

![color_diff](https://user-images.githubusercontent.com/1515991/102861557-de743a00-4455-11eb-96cc-c96c8dff7c74.png)

The result I am getting is `0`.

**Comment by lpatiny** [comment]
You need to define the alpha value you are searching. By default it is 1 ... which is weird.

image.countAlphaPixels({ alpha: 255 });

@targos Should we change the default value to the maxValue ? https://github.com/image-js/image-js/blob/9eb6e7feee304140b6648e003e18f7497a7e7dab/src/image/compute/countAlphaPixels.js#L10
It would be technically a breaking change even if the default value currently does not make sense.

**Comment by targos** [comment]
The goal of this method seems to be counting the number of transparent pixels, so the default should be `0`, not `255`.

**Comment by santosh** [comment]
Hey guys. I haven't got a chance to work with image.js lately. But if this change has been made in recent releases, can we close this issue?

**Comment by santosh** [comment]
Closing this issue under a cleanup campaign.
