### ISSUE TITLE
Load image via URL

### ISSUE THREAD

**Issue by CutieCat6778** [image-js/image-js#551]
Is there any way to load an Image via URL with the NPM.js package?

```js
const { Image } = require('image-js');
const img = await Image.load('https://example.com/example.png');
```

**Comment by targos** [comment]
This is currently not possible directly with image-js.
You can easily do it by combining it with a library. For example, using [`got`](https://github.com/sindresorhus/got)

```js
const { Image } = require('image-js');
const got = require('got');
const response = await got('https://example.com/example.png', { responseType: 'buffer' });
const img = await Image.load(response.body);
```

If you would like to contribute with a pull request, I think the best would be to add something to https://github.com/image-js/image-js/blob/bbec15dfab423b29cd8105e5d3ff52e143912967/src/image/core/environment.js#L26-L33, like check if the path starts with `http://` or `https://` and in that case make a request.

**Comment by CutieCat6778** [comment]
Well I figured out how to get the image frm url with `request` package. But thanks for helping me :))
