### ISSUE TITLE
16bit 1channel grayscale not working as expected

### ISSUE THREAD

**Issue by trifox** [image-js/image-js#553]
width and height are integers according to uint16 array, the result is a rgb encoded image, although bitdepth and components look correctly encoded
 
const image = new Image(width, height, uint16data, {bitDepth: 16, components: 1, alpha: 0})
 return image.toBlob()

**Comment by targos** [comment]
The `toBlob` method uses the browser's canvas API to get a Blob. This only works with 8-bit RGBA images, so whatever was the input format, it will always be converted to 8-bit RGBA.

**Comment by trifox** [comment]
i see, is there any possibility to create a 16bit png in the browser?

**Comment by targos** [comment]
It should work with `toBuffer()` and `toBase64()`. They use a JavaScript PNG encoder by default (https://github.com/image-js/fast-png).

**Comment by trifox** [comment]
basically this issue can be closed, its working just fine using toBuffer(), i could adjust the documentation if that would be of any help, and even include a console.assert to trigger a warning that 16bit is not pertained when using toBlob()
