### ISSUE TITLE
Image from matrix

### ISSUE THREAD

**Issue by maasencioh** [image-js/image-js#555]
If I have a matrix of values (temperatures for example), I could use [D3 color scaler](https://github.com/d3/d3-scale-chromatic) in order to get a matrix of RGB values. How could be possible to transform this into an image? I've seen that the constructor allows an array of data, but I can't see an example of how to use this in the documentation.

**Comment by targos** [comment]
The array of data should be a typed array with the values (row by row).
For example, to create a 2x3 RGB image, it would be:
```
// size = rows * columns * channels
const data = new Uint8Array(2*3*3)
const image = new Image(2, 3, data)
```

**Comment by maasencioh** [comment]
Thank you, do you think that this should be in any part of the documentation? If you help me pointing a little bit the direction I could add it

**Comment by lpatiny** [comment]
Seems there is already some documentation but you may add an example if you want https://image-js.github.io/image-js/
