### ISSUE TITLE
Support EXIF Orientation

### ISSUE THREAD

**Issue by fabb** [image-js/image-js#561]
When loading an image with EXIF orientation, image-js just ignores it. This results in `rotate` calls not rotating to the desired orientation when wanting to rotate relative to the way the image is shown in an `<img>` element.

**Comment by targos** [comment]
Hello, I can have a look. Could you post such an image to this issue, so we can use it in a test case?

**Comment by fabb** [comment]
Sure, here is one (i hope github does not recompress it and strip exif):
![C1CCC7C4-9F08-4196-8926-C79E23E37D4A](https://user-images.githubusercontent.com/153960/125074378-80d7d000-e0bd-11eb-8965-e266aa14b613.jpeg)

**Comment by fabb** [comment]
I'm trying to implement a workaround until the exif orientation is supported and automatically applied.

I've seen that image-js already provides a `meta` field, and for this particular image, it contains both an `exif` and a `tiff` object:
![Screenshot 2021-07-09 at 15 04 37](https://user-images.githubusercontent.com/153960/125082246-47a45d80-e0c7-11eb-917e-168cd3093ff4.png)

Looks like the tiff meta data also contains the orientation. The exif meta data is encoded, I yet need to find out how to decode it. The question is if I can always rely on the tiff meta data to be there (I guess not), or if I should implement support for both tiff orientation and exif orientation.

**Comment by targos** [comment]
I just opened a PR to fix this: https://github.com/image-js/image-js/pull/563

**Comment by fabb** [comment]
Oh wow, that‘s about the quickest open source response i have ever seen 🤩
