### ISSUE TITLE
readStripData fails because stripByteCounts is undefined in IDF 

### ISSUE THREAD

**Issue by seb8doh** [image-js/image-js#577]
While trying to open 16 bits images I noticed that sometimes stripByteCounts is undefined in IDF and readStripData fails because of that.
In my case the image contains only one strip so setting stripByteCounts to the size of the buffer (minus the offset) is fixing the issue but not sure you'll choose this approach.
 ` const stripByteCounts = ifd.stripByteCounts ? ifd.stripByteCounts : [this.byteLength - this.byteOffset - stripOffsets[0]];`

Thanks

**Comment by seb8doh** [comment]
Sorry, wrong place for this issue

**Comment by targos** [comment]
Would you be able to provide a public test image (for test cases)?

**Comment by seb8doh** [comment]
I recreated the issue to https://github.com/image-js/tiff/issues/38, I don't have a test public image but I'll try to create one.
