### ISSUE TITLE
如何保存cmyk图片

### ISSUE THREAD

**Issue by 0reoo** [image-js/image-js#579]
我需要将canvas图片保存为cmyk模式，但是执行了.cmyk()后再进行.toBase64()就会报错，请问有什么办法可以保存cmyk模式的图片吗?谢谢

**Comment by maasencioh** [comment]
what kind of error are you getting? do you have a test code to share?

**Comment by YakumoAoi** [comment]
> what kind of error are you getting? do you have a test code to share?

`    let image = await IJS.Image.load(imageUrl);
    if (image.colorModel === 'CMYK') return imageUrl
    let CMYKImage = image.cmyk()
    return CMYKImage.toDataURL();
`
error message:
RangeError: unsupported number of channels: 5
