### ISSUE TITLE
Support for decoding TIFF with more than 3 channels

### ISSUE THREAD

**Issue by lahr-ul** [image-js/image-js#581]
image-js version: 0.33.1

I have a 16bit TIFF file with 24 image channels. When I load it with `var i = await Image.load('my_image.tif')` I get the following Exception:

```
Uncaught RangeError: incorrect data size: 25536. Should be 1064
    at new Image (.../node_modules/image-js/lib/image/Image.js:267:15)
    at getImageFromIFD (.../node_modules/image-js/lib/image/core/load.js:250:12)
    at loadTIFF .../node_modules/image-js/lib/image/core/load.js:202:12)
    at loadBinary (.../node_modules/image-js/lib/image/core/load.js:67:16)
    at .../node_modules/image-js/lib/image/core/load.js:97:12
``` 

The image has a height of 38 and a width of 28. So all 24 channels are read (38 * 28 * 24 = 25536) but image-js expects just one (38 * 28 * 1 = 1064).

**Comment by targos** [comment]
According to the location of the error, the TIFF was actually correctly decoded by the underlying [`tiff`](https://github.com/image-js/tiff) library, so if you just need the raw data, you can use `tiff.decode()` directly.
If you expect `image-js` to load and understand this image, then what is expected? This library cannot manipulate images with more than 4 channels.
