### ISSUE TITLE
jpeg encoding in the browser does not work

### ISSUE THREAD

**Issue by onuraltas** [image-js/image-js#612]
After resizing an image I'm trying to encode as JPEG with toDataURL and toBlob methods gives this error;

Uncaught ReferenceError: Buffer is not defined
    at JPEGEncoder.encode (encoder.js:727:1)

**Comment by Rulsky** [comment]
looks like image-js expects that Buffer is somehow already present in global scope. The solution is to add buffer on your own.

1. install browser's implementation of buffer:
```
npm i buffer
```

2. import it somewhere and assign to window object:
```
window.Buffer = window.Buffer || require("buffer").Buffer;
```

in my case I did it the same file where I import image-js

**Comment by onuraltas** [comment]
thank you.
