### ISSUE TITLE
Is there a way to scale a png like gdal scale with src min/max destination min/max?

### ISSUE THREAD

**Issue by delebash** [image-js/image-js#620]
See https://gdal.org/programs/gdal_translate.html#cmdoption-gdal_translate-scale.

Thanks!

**Comment by stropitek** [comment]
I don't know how gdal behaves when scaling images but have you looked at the `resize` method?

**Comment by delebash** [comment]
Yes but it does not have the option to scale by source and destination size.

**Comment by stropitek** [comment]
Actually `resize` in ijs and `scale` in gdal are unrelated.

The former changes the size of the image, the latter scales the pixel values to a different range.

We have the `level` method for that. But it does not have the possibility to provide the source min and max, only the destination.

We already fixed that in https://github.com/image-js/image-js-typescript, which is unstable but will eventually replace image-js.
