### ISSUE TITLE
"Interlace method 1 not supported" Error in browser(Firefox)

### ISSUE THREAD

**Issue by rafa-br34** [image-js/image-js#626]
![image](https://github.com/image-js/image-js/assets/111343658/087994fc-3a78-4599-b578-6096981b620b)

Image used:
![image-7](https://github.com/image-js/image-js/assets/111343658/6b913fae-c594-44f3-9c75-91b5ddc7427a)

I'm using `await IJS.Image.load(Data)` (`Data` is the raw image data loaded using the `FileReader.readAsArrayBuffer` method) to load the image.

**Comment by stropitek** [comment]
The library we use to decode pngs does not support interlacing yet.

See https://github.com/image-js/fast-png/issues/28
